# Make sure to check the documentation at https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: itero

before:
  hooks:
    - go mod download

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: itero
    main: ./cmd/itero
    binary: itero
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags: 
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: itero
    ids:
      - itero
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers_v2:
  - id: itero
    ids:
      - itero
    images:
      - "docker.io/b0risdvlpr/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
    dockerfile: Dockerfile.release
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
    labels: &oci
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.description: "Self-hosted, Kubernetes-native feature flag management backend."
      org.opencontainers.image.url: "https://github.com/borisdvlpr/itero"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.licenses: "Apache-2.0"
    annotations: *oci

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

report_sizes: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^ci"
      - "^chore"
      - "^docs"
      - "^refactor"
      - "^style"
      - "^test"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  prerelease: auto
  footer: |
    ## Container images

    ```sh
    docker pull docker.io/b0risdvlpr/itero:{{ .Version }}
    ```
