CREATE TABLE flags
(
    id         UUID PRIMARY KEY,
    project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    key        TEXT NOT NULL CHECK (key ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$'),
    name        TEXT NOT NULL,
    description TEXT,
    type        TEXT NOT NULL CHECK (type IN ('boolean', 'string', 'integer', 'float', 'object')),
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
    version     BIGINT NOT NULL DEFAULT 1,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (project_id, key),
    UNIQUE (project_id, id),
    UNIQUE (id, type)
);

CREATE TRIGGER flags_touch
    BEFORE UPDATE
    ON flags
    FOR EACH ROW EXECUTE FUNCTION touch_row();

CREATE TRIGGER flags_bump_revision
    AFTER UPDATE
    ON flags
    FOR EACH ROW EXECUTE FUNCTION bump_revision_from_flag();

COMMENT
ON COLUMN flags.id IS
    'UUIDv7, generated by the application.';

COMMENT
ON COLUMN flags.version IS
    'Optimistic concurrency token, incremented by touch_row() on every UPDATE. '
    'Guard writes with WHERE id = $1 AND version = $2.';
