CREATE TABLE projects (
    id          UUID PRIMARY KEY,
    key         TEXT NOT NULL UNIQUE
                CHECK (key ~ '^[a-z0-9][a-z0-9._-]{0,62}$'),
    name        TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER projects_set_updated_at
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN projects.id IS
    'UUIDv7, generated by the application. See docs/schema.md.';

INSERT INTO projects (id, key, name, description) VALUES (
    '01920000-0000-7000-8000-000000000001',
    'default',
    'Default',
    'Implicit project created by the initial migration.'
);
