CREATE TABLE audit_log
(
    id            UUID PRIMARY KEY,
    project_id    UUID NOT NULL,
    resource_type TEXT NOT NULL CHECK (resource_type IN (
                                                         'project', 'environment', 'flag',
                                                         'flag_environment', 'variant', 'targeting_rule'
        )),
    resource_id   UUID NOT NULL,
    action        TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')
) ,
    actor         TEXT,
    before        JSONB CHECK (before IS NULL OR jsonb_typeof(before) = 'object'),
    after         JSONB CHECK (after IS NULL OR jsonb_typeof(after) = 'object'),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_resource
    ON audit_log (resource_type, resource_id, created_at DESC);

CREATE INDEX idx_audit_log_project_created
    ON audit_log (project_id, created_at DESC);

COMMENT
ON TABLE audit_log IS
    'Append-only. The application exposes no UPDATE or DELETE path; rows leave '
    'only through the retention sweep documented in docs/schema.md.';

COMMENT
ON COLUMN audit_log.id IS
    'UUIDv7, generated by the application. This is the one append-heavy table '
    'in the schema, so a time-ordered prefix keeps inserts at the right-hand '
    'edge of the B-tree instead of scattering them the way UUIDv4 does.';
