CREATE TABLE environments
(
    id         UUID PRIMARY KEY,
    project_id UUID NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    key        TEXT NOT NULL CHECK (key ~ '^[a-z0-9][a-z0-9._-]{0,62}$'),
    name       TEXT NOT NULL,
    revision   BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (project_id, key),
    UNIQUE (project_id, id)
);

CREATE TRIGGER environments_set_updated_at
    BEFORE UPDATE
    ON environments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT
ON COLUMN environments.id IS
    'UUIDv7, generated by the application.';

COMMENT
ON COLUMN environments.revision IS
    'Monotonic counter over every flag, variant and rule in this environment. '
    'Bumped by triggers on flags, flag_environments, variants and '
    'targeting_rules; each bump emits NOTIFY on channel itero_flag_config.';
